package com.kafitra.demo2;

import com.lynx.tasm.LynxEnv;

import com.kafitra.lynxdeviceinfo.LynxDeviceInfoModule;
import com.kafitra.lynxstorage.LynxStorageModule;

/**
 * Auto-generated by @kafitra/lynx-autolink.
 * Run `npx @kafitra/lynx-cli link` to regenerate.
 * DO NOT EDIT MANUALLY.
 */
public class LynxAutolinkRegistry {
    public static void registerAll() {
        LynxEnv.inst().registerModule(
            "LynxDeviceInfo",
            LynxDeviceInfoModule.class
        );
        LynxEnv.inst().registerModule(
            "LynxStorage",
            LynxStorageModule.class
        );
    }
}
