package com.kafitra.demo;

import com.lynx.tasm.LynxEnv;

import com.kafitra.lynxdeviceinfo.LynxDeviceInfoModule;

/**
 * Auto-generated by @kafitra/lynx-autolink.
 * Run `npx @kafitra/lynx-cli link` to regenerate.
 * DO NOT EDIT MANUALLY.
 */
public class LynxAutolinkRegistry {
    public static void registerAll() {
        LynxEnv.inst().registerModule(
            "LynxDeviceInfo",
            LynxDeviceInfoModule.class
        );
    }
}
